services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\Vcfqr\:
    resource: '../Classes/*'

  TRAW\Vcfqr\Utility\ConfigurationUtility:
    public: true

  TRAW\Vcfqr\EventListeners\DatabaseSchemaEventListener:
    tags:
      - name: event.listener
        identifier: 'vcfqr-ttaddress'
        method: performNecessarySchemaUpdate
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
